# Site settings
title: Jorge C. Galarza
description: Jekyll Theme Minimal Resume
# baseurl: "https://github.com/jorgegalarza1/Portfolio_Projects"
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jorge C. Galarza Prieto
user_description: Hello, my name is Jorge C. Galarza Prieto and I am a Ph. D. Candidate in the Department of Biology at New Mexico State University, where I am also an NIH Scholar and Graduate Research Assistant. I received my B.S. in Human Nutrition and Dietetic Sciences December 2015, and my M.S in Frood Science Technology and Engineering in May 2019.   
user_title: Biology | Data Science and Analytics | Statistics | Food Science Technology and Engineering | Human Dietetics
email: jorge_galarza_1@outlook.com
# twitter_username: lorem_ipsum
instagram_username: jc.galarza
# facebook_username: 
linkedin_username: jorge-g-97008b22b
github_username:  jorgegalarza1
# medium_username: 
# medium_url: 
# gplus_username: 

exclude: ['package.json', 'src' , 'node_modules']
