# Site settings
title: Jorge Carlos Galarza Prieto, PhD
description: Jekyll Theme Minimal Resume
# baseurl: "https://github.com/jorgegalarza1/Portfolio_Projects"
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# User settings
username: Jorge Carlos Galarza Prieto, PhD
user_description: Dynamic and versatile biologist with 5+ years of experience leading bioinformatics-driven projects across immunology, microbiology, and molecular biology. Proven expertise in analyzing complex multi-omics datasets to drive actionable biological insights. Adept at integrating wet-lab and dry-lab workflows, bridging experimental and computational biology. Recognized for spearheading cross-functional, stakeholder-focused projects, fostering collaboration across academic, industry, and federal sectors. Exceptional leadership skills demonstrated through mentoring students, managing teams, and independently driving large-scale research projects with $4 million in secured funding(USDA grant Award#2014-38422-22084, NIH grant Award#R25GM061222). Accomplished communicator with a track record of presenting at international conferences, leading targeted lab meetings, and translating complex scientific data for diverse audiences and grant proposals. Thrives in independent and collaborative settings, with a passion for data-driven discovery and translating sequencing data into meaningful scientific and clinical applications.
user_title: Bioinformatics | Immunology | Microbiology | Molecular Biology
email: jorge_galarza_1@icloud.com
# twitter_username: lorem_ipsum
# instagram_username: jc.galarza
# facebook_username: 
# linkedin_username: jorgecgalarzap
github_username:  jorgegalarza1
# medium_username: 
# medium_url: 
# gplus_username: 

exclude: ['package.json', 'src' , 'node_modules']
