# Site settings
title: Jorge C. Galarza, PhD
description: Jekyll Theme Minimal Resume
# baseurl: "https://github.com/jorgegalarza1/Portfolio_Projects"
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# User settings
username: Jorge C. Galarza, PhD
user_description: A very detail-oriented and organized team player with extensive research, wet lab, dry lab, molecular biology, microbiology, and bioinformatics experience. I have a B.S. in Human Nutrition and Dietetic Sciences, a M.S. in Food Science Technology and Engineering, and a Ph.D. in Biology. My M.S. work was fully funded by the United States Department of Agriculture (USDA) under the Southwest Agriculture and Food Security Education (SAFE) grant (Award#2014-38422-22084), and my Ph.D. was fully funded by the National Institutes of Health (NIH) under the Research Initiative for Scientific Enhancement (RISE) grant (Award#R25GM061222).<br><br>In my most recent role, I conducted on- and off-site research, wet lab experiments, and bioinformatics analysis through R, Python, Bash and SQL.<br><br>My skills and experience as a researcher, biologist, educator, data analyst, data scientist, biostatistician, bioinformatician, make me well-suited to work across various sectors and spaces.<br><br>Outside of my professional life, I spend most of my weekends reading, hiking, biking, working out, trying out at a new restaurant, taking a random class on an interesting topic, enjoying a good Harry Potter marathon, watching Dune for the 100th time or playing video games.<br><br>I am a simple guy, with a scientific mind.
user_title: Molecular Biology | Microbiology | Bioinformatics | Food Science Technology and Engineering | Human Dietetics
email: jorge_galarza_1@icloud.com
# twitter_username: lorem_ipsum
instagram_username: jc.galarza
# facebook_username: 
linkedin_username: jorgecgalarzap
github_username:  jorgegalarza1
# medium_username: 
# medium_url: 
# gplus_username: 

exclude: ['package.json', 'src' , 'node_modules']
