# Site settings
title: Jorge C. Galarza
description: Jekyll Theme Minimal Resume
# baseurl: "https://github.com/jorgegalarza1/Portfolio_Projects"
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# User settings
username: Jorge Galarza Prieto, Ph.D.
user_description: A very detail-oriented and organized team player with extensive research, wet lab, dry lab, molecular biology, microbiology, and bioinformatics experience. I have a B.S. degree in Human Dietetics, a M.S. in Food Science Technology and Engineering, and lastly a Ph.D. in Biology. My M.S. work was fully funded by the United States Department of Agriculture under the Southwest Agriculture and Food Security Education (SAFE) grant (Award#2014-38422-22084), and my Ph.D. work was fully funded by the National Institutes of Health under the Research Initiative for Scientific Enhancement (RISE) grant (Award#R25GM061222).
user_title: Molecular Biology | Microbiology | Bioinformatics | Food Science Technology and Engineering | Human Dietetics
email: jorge_galarza_1@icloud.com
# twitter_username: lorem_ipsum
instagram_username: jc.galarza
# facebook_username: 
linkedin_username: jorgecgalarzap
github_username:  jorgegalarza1
# medium_username: 
# medium_url: 
# gplus_username: 

exclude: ['package.json', 'src' , 'node_modules']
