# Site settings
title: Jorge C. Galarza Prieto
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jorge C. Galarza Prieto
user_description: New Mexico State University
user_title: Biology | Data Science | Food Engineering | Human Dietetics
email: jorge_galarza_1@outlook.com
# twitter_username: lorem_ipsum
instagram_username: jc.galarza
# facebook_username: 
linkedin_username: jorge-g-97008b22b
github_username:  jorgegalarza1
# medium_username: 
# medium_url: 
# gplus_username: 

exclude: ['package.json', 'src' , 'node_modules']
