# Site settings
title: Jorge C. Galarza
description: Jekyll Theme Minimal Resume
# baseurl: "https://github.com/jorgegalarza1/Portfolio_Projects"
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jorge C. Galarza Prieto
user_description: Hello, my name is Jorge C. Galarza Prieto and I am a Biomedical Scientist, PhD Candidate at New Mexico State University where my research is funded by the NIH (Research Initiative for Scientific Enhancement).
user_title: Biomedicine | Data Science and Analytics | Statistics | Food Science Technology and Engineering | Human Dietetics
email: jorge_galarza_1@outlook.com
# twitter_username: lorem_ipsum
instagram_username: jc.galarza
# facebook_username: 
linkedin_username: jorge-g-97008b22b
github_username:  jorgegalarza1
# medium_username: 
# medium_url: 
# gplus_username: 

exclude: ['package.json', 'src' , 'node_modules']
